(repository
  (url ".")
  (name "example repository")
  (package
    (name (foo))
    (version "1.0")
    (url "foo.tgz")
    (library
      (name (gibber foo))
      (path "gibber/foo.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "an example library")
      (license BSD-style)
      (depends)
      (use-for final))
    (library
      (name (example-tests foo-tests))
      (path "example-tests/foo-tests.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "tests for an example pacakge")
      (license BSD-style)
      (depends)
      (use-for test)))
  (package
    (name (bar))
    (version "1.0")
    (url "bar.tgz")
    (library
      (name (gibber bar))
      (path "gibber/bar.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "an example library")
      (license BSD-style)
      (depends)
      (use-for final))
    (library
      (name (gibber baz))
      (path "gibber/baz.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "an example library")
      (license BSD-style)
      (depends)
      (use-for final))
    (library
      (name (example-tests bar-baz-tests))
      (path "example-tests/bar-baz-tests.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (manual)
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "tests for an example package")
      (license BSD-style)
      (depends)
      (use-for test))))
